-- fix-tests.lua
-- Workflow: run tests, reason about failures, apply a fix.
-- The agent can ONLY reason — it cannot execute capabilities directly.
-- The runtime executes every capability. The agent stays in its lane.

local test_scope = scope("test-scope", {
    include      = { "src/**", "tests/**", "*.go" },
    exclude      = { ".env", "secrets/**" },
    capabilities = { "process.execute", "filesystem.read", "filesystem.write" },
})

workflow("fix-tests", {
    scope = test_scope,

    steps = {
        step("run-tests", execute("process.execute", {
            cmd = "go test ./... 2>&1",
        })),

        step("read-source", execute("filesystem.read", {
            path = "main.go",
        })),

        step("analyze-failures", reason(
            "Analyze the test output and source code. Identify the root cause of any failures. " ..
            "Propose a precise fix. Be specific about which lines need to change and why."
        )),

        step("write-fix", execute("filesystem.write", {
            path    = "fix_report.md",
            content = "# Fix Report\n\nGenerated by splash workflow: fix-tests",
        })),

        step("verify", execute("process.execute", {
            cmd = "go build ./... 2>&1",
        })),
    }
})
